from Node import Node

a = Node(0)
b = Node(100)
c = Node(169)
d = Node(45)
e = Node(7)
e = Node(87)
f = Node(45)
g = Node(41)
h = Node(14)
i = Node(4)
j = Node(34)
k = Node(89)
l = Node(21)
m = Node(4)
n = Node(6)
o = Node(9)
p = Node(10)

a.addneighbors(g,b,e)
b.addneighbors(a,d)
c.addneighbors(k,d)
d.addneighbors(b,c,i,f)
e.addneighbors(a,l)
f.addneighbors(d)
g.addneighbors(a,h)
h.addneighbors(g,n)
i.addneighbors(d,o)
j.addneighbors(l)
k.addneighbors(c)
l.addneighbors(e,j)
m.addneighbors(p)
n.addneighbors(h)
o.addneighbors(i)
p.addneighbors(m)
